sudo: required
language: go
go:
  - 1.7

env:
  - PLATFORM=android-arm
  - PLATFORM=android-x64
  - PLATFORM=android-x86
  - PLATFORM=darwin-x64
  - PLATFORM=linux-arm
  - PLATFORM=linux-armv7
  - PLATFORM=linux-arm64
  - PLATFORM=linux-x64
  - PLATFORM=linux-x86
  - PLATFORM=windows-x64
  - PLATFORM=windows-x86
  - DEP_VERSION=0.5.0
  
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

services:
  - docker

script:
  - go tool vet -unsafeptr=false .
  - make libs
  - make $PLATFORM
  - |
    echo tpr ${TRAVIS_PULL_REQUEST} and tt ${TRAVIS_TAG}
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -n "${TRAVIS_TAG}" ]; then
      travis_retry ./push-binaries.sh
    fi
