[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "v1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "v1.5.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "v29.0.2"

[[constraint]]
  name = "github.com/charly3pins/libtorrent-go"
  branch = "master"
  
[[constraint]]
  name = "github.com/cloudflare/ahocorasick"
  branch = "master"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/zeebo/bencode"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/jmcvetta/napping"
  version = "v3.2.0"

[[constraint]]
  name = "github.com/kolo/xmlrpc"
  branch = "master"
